### ISSUE TITLE
local data (offline) mode

### ISSUE THREAD

**Issue by linuxcaffe** [DavidBadura/doThings#43]
Would it be possible to have data stored locally, so that a web instance on laptop or mobile could continue to have access to full task list, even without an internet connection?

I suppose this feature would require syncing with the taskserver API, on reconnection, not sure of the mechanics here, but I AM sure that not everyone is "always on".

**Comment by tolry** [comment]
That would be really hard, I guess. Since doThings does not perform any actions by itself, rather passes them on to TW. So reports and filtering in general would have to be reimplemented, as well as all write operations and everything keeping in mind user specific configuration options.

I agree: an offline mode would be really great (perform time consuming reviews on the plane or anywhere else without an internet connection), but I am afraid doThings would have to mutate from being a very thin layer of executing TW commands and displaying the output to a complete reimplementation, only sharing data storage via taskserver.

@DavidBadura what are your thoughts on this?

**Comment by DavidBadura** [comment]
Sorry for the late answer. I have forgotten it...
I don't think it is possible without copying the business logic.

Later i will add ember js. So i could theoretically save the actions and run them later. More will not be possible, sorry.
